// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to cloud production values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ipizfawpzzwdltcbskim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwaXpmYXdwenp3ZGx0Y2Jza2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTg0MDEwNTQsImV4cCI6MjAzMzk3NzA1NH0.DYOrE7D3-YurEMsAfT0LZ6o7nnS2TS7oQIEYcJQ_fpo";

// Service role key for admin operations (get this from your Supabase project settings -> API)
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY;

// Regular client for normal operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Admin client for server-side operations (creating users, etc.)
export const supabaseAdmin = SUPABASE_SERVICE_ROLE_KEY 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })
  : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// import { supabaseAdmin } from "@/integrations/supabase/client"; // For admin operations